# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: git config user.email "nick.marks@eagletg.com" && git config user.name "Nick Marks"
  displayName: 'Set git user info'

- script: yarn
  displayName: 'Install Dependencies'

- script: npx run-s build:ng-timer
  displayName: 'Build ng-timer'

- script: npx run-s build:ng-timer-docs
  displayName: 'Build ng-timer-docs'

- script: npx run-s release
  displayName: 'Release ng-timer to npm'

- script: npx run-s deploy
  displayName: 'Deploy ng-timer-docs to github pages'
